version: '2.4'
services:
  builder:
    build: builder
    container_name: builder_cont
    volumes:
      - ./shared/:/shared/
  runner:
    build: runner
    container_name: runner_cont
    ports:
      - "8080:8080"
    volumes:
      - ./shared/:/usr/local/tomcat/webapps/
    depends_on:
      - builder

  
