version: '3.8'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password 
    volumes:
      - /var/db/mysql/:/var/lib/mysql             
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "dd"
      MYSQL_USER: "acp4pogynvaeidfj"
      MYSQL_PASSWORD: "jc31d2qyy7h9jv5jn1u9uosjksxzaizw"      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  web:
    build: web
    container_name: paas
    ports:
      - "8080:8080"    
    depends_on:
      - db


  
