FROM openjdk:8u151-stretch

# Install pacakges
RUN apt-get update

# Install ssh
RUN apt-get -y install openssh-client


# Install docker 18.03
RUN apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common

RUN curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz \
  && tar xzvf docker-17.04.0-ce.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -r docker docker-17.04.0-ce.tgz


# Clear cache
RUN apt-get clean